# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Ryubing.Ryujinx.Canary
PackageVersion: 1.2.356
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: publish\Ryujinx.exe
  PortableCommandAlias: Ryujinx
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Ryubing/Canary-Releases/releases/download/1.2.356/ryujinx-canary-1.2.356-win_x64.zip
  InstallerSha256: 038411651B865105C38AAF6793E68D3D7B34A3C46D016F22209B47B44DFC07B0
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-02-08
